###############################################################################
# SVOTC package (YAML engine)
# - Comments/instructions in English (per request)
# - Logic: stable + explainable (no PI integrator)
# - Uses Nordpool Tibber attributes: current_price, raw_today, raw_tomorrow
###############################################################################

input_select:
  svotc_mode:
    name: "SVOTC Mode"
    options:
      - Off
      - Smart
      - Vacation
    initial: Smart

input_number:
  svotc_brake_aggressiveness:
    name: "SVOTC Brake aggressiveness"
    min: 0
    max: 5
    step: 1
    mode: slider
    initial: 4

  svotc_heat_aggressiveness:
    name: "SVOTC Heat aggressiveness"
    min: 0
    max: 5
    step: 1
    mode: slider
    initial: 0

  svotc_comfort_temperature:
    name: "SVOTC Comfort temperature"
    min: 15
    max: 25
    step: 0.1
    mode: box
    initial: 20.0

  svotc_vacation_temperature:
    name: "SVOTC Vacation temperature"
    min: 10
    max: 25
    step: 0.1
    mode: box
    initial: 17.0

  svotc_requested_offset_c:
    name: "SVOTC Requested offset (C)"
    min: -10
    max: 10
    step: 0.1
    mode: box
    initial: 0.0

  svotc_applied_offset_c:
    name: "SVOTC Applied offset (C)"
    min: -10
    max: 10
    step: 0.1
    mode: box
    initial: 0.0

  # Max delta per engine tick (degC). With 1 min tick, 0.5C is a sane start.
  svotc_max_delta_per_step_c:
    name: "SVOTC Max delta per step (C)"
    min: 0.1
    max: 5
    step: 0.1
    mode: box
    initial: 0.5

input_text:
  svotc_reason_code:
    name: "SVOTC Reason code"
    initial: "NEUTRAL"

  # Stable price state after dwell: brake/cheap/neutral
  svotc_last_price_state:
    name: "SVOTC Last price state"
    initial: "neutral"

  # Pending candidate during dwell (must exist to avoid resetting dwell every minute)
  svotc_pending_price_state:
    name: "SVOTC Pending price state"
    initial: "neutral"

input_datetime:
  svotc_last_price_state_changed:
    name: "SVOTC Last price state changed"
    has_date: true
    has_time: true

template:
  - sensor:
      #########################################################################
      # Source sensors (single place to configure)
      #########################################################################
      - name: "SVOTC Src Indoor"
        unique_id: svotc_src_indoor
        unit_of_measurement: "째C"
        device_class: temperature
        state_class: measurement
        state: >
          {{ states('sensor.inomhusmedel') | float(none) }}
        availability: >
          {{ states('sensor.inomhusmedel') not in ['unknown','unavailable','none',''] }}

      - name: "SVOTC Src Outdoor"
        unique_id: svotc_src_outdoor
        unit_of_measurement: "째C"
        device_class: temperature
        state_class: measurement
        state: >
          {{ states('sensor.temperatur_nu') | float(none) }}
        availability: >
          {{ states('sensor.temperatur_nu') not in ['unknown','unavailable','none',''] }}


      - name: "SVOTC Src Current Price"
        unique_id: svotc_src_current_price
        unit_of_measurement: "SEK/kWh"
        device_class: monetary
        state: >
          {% set p = state_attr('sensor.nordpool_tibber', 'current_price') %}
          {% if p is number %}
            {{ p | round(3) }}
          {% else %}
            {{ this.state | float(0) }}
          {% endif %}
        availability: >
          {{ state_attr('sensor.nordpool_tibber', 'current_price') is number }}

      #########################################################################
      # Dynamic target temperature
      #########################################################################
      - name: "SVOTC Dynamic target temperature"
        unique_id: svotc_dynamic_target_temperature
        unit_of_measurement: "째C"
        state: >
          {% set mode = states('input_select.svotc_mode') %}
          {% if mode == 'Vacation' %}
            {{ states('input_number.svotc_vacation_temperature') | float(0) }}
          {% else %}
            {{ states('input_number.svotc_comfort_temperature') | float(0) }}
          {% endif %}

      #########################################################################
      # Price percentiles (p30/p70/p80) from merged raw_today+raw_tomorrow
      # - Uses sensor.nordpool_tibber attributes raw_today/raw_tomorrow
      #########################################################################
      - name: "SVOTC P30"
        unique_id: svotc_p30
        unit_of_measurement: ""
        state: >
          {% set today = state_attr('sensor.nordpool_tibber', 'raw_today') %}
          {% set tomorrow = state_attr('sensor.nordpool_tibber', 'raw_tomorrow') %}
          {% set arr = [] %}
          {% for it in (today or []) %}
            {% set v = (it.value if it is mapping and 'value' in it else none) %}
            {% if v is number %}{% set arr = arr + [v] %}{% endif %}
          {% endfor %}
          {% for it in (tomorrow or []) %}
            {% set v = (it.value if it is mapping and 'value' in it else none) %}
            {% if v is number %}{% set arr = arr + [v] %}{% endif %}
          {% endfor %}
          {% if arr | length < 10 %}
            {{ states('sensor.svotc_p30') | float(0) }}
          {% else %}
            {% set s = arr | sort %}
            {% set idx = ((s|length) * 0.30) | int %}
            {{ s[min(idx, (s|length)-1)] | round(2) }}
          {% endif %}

      - name: "SVOTC P70"
        unique_id: svotc_p70
        unit_of_measurement: ""
        state: >
          {% set today = state_attr('sensor.nordpool_tibber', 'raw_today') %}
          {% set tomorrow = state_attr('sensor.nordpool_tibber', 'raw_tomorrow') %}
          {% set arr = [] %}
          {% for it in (today or []) %}
            {% set v = (it.value if it is mapping and 'value' in it else none) %}
            {% if v is number %}{% set arr = arr + [v] %}{% endif %}
          {% endfor %}
          {% for it in (tomorrow or []) %}
            {% set v = (it.value if it is mapping and 'value' in it else none) %}
            {% if v is number %}{% set arr = arr + [v] %}{% endif %}
          {% endfor %}
          {% if arr | length < 10 %}
            {{ states('sensor.svotc_p70') | float(0) }}
          {% else %}
            {% set s = arr | sort %}
            {% set idx = ((s|length) * 0.70) | int %}
            {{ s[min(idx, (s|length)-1)] | round(2) }}
          {% endif %}

      - name: "SVOTC P80"
        unique_id: svotc_p80
        unit_of_measurement: ""
        state: >
          {% set today = state_attr('sensor.nordpool_tibber', 'raw_today') %}
          {% set tomorrow = state_attr('sensor.nordpool_tibber', 'raw_tomorrow') %}
          {% set arr = [] %}
          {% for it in (today or []) %}
            {% set v = (it.value if it is mapping and 'value' in it else none) %}
            {% if v is number %}{% set arr = arr + [v] %}{% endif %}
          {% endfor %}
          {% for it in (tomorrow or []) %}
            {% set v = (it.value if it is mapping and 'value' in it else none) %}
            {% if v is number %}{% set arr = arr + [v] %}{% endif %}
          {% endfor %}
          {% if arr | length < 10 %}
            {{ states('sensor.svotc_p80') | float(0) }}
          {% else %}
            {% set s = arr | sort %}
            {% set idx = ((s|length) * 0.80) | int %}
            {{ s[min(idx, (s|length)-1)] | round(2) }}
          {% endif %}

      #########################################################################
      # Current price (from SVOTC source sensor)
      #########################################################################
      - name: "SVOTC Current price"
        unique_id: svotc_current_price
        unit_of_measurement: "SEK/kWh"
        device_class: monetary
        state: >
          {{ states('sensor.svotc_src_current_price') | float(none) }}
        availability: >
          {{ states('sensor.svotc_src_current_price') not in ['unknown','unavailable','none',''] }}

      #########################################################################
      # Raw price state: brake/cheap/neutral (no dwell)
      # - Uses P80 for brake and P30 for cheap
      #########################################################################
      - name: "SVOTC Raw price state"
        unique_id: svotc_raw_price_state
        state: >
          {% set mode = states('input_select.svotc_mode') %}
          {% if mode == 'Off' %}
            off
          {% else %}
            {% set p = states('sensor.svotc_src_current_price') | float(none) %}
            {% set p30 = states('sensor.svotc_p30') | float(none) %}
            {% set p80 = states('sensor.svotc_p80') | float(none) %}
            {% if p is number and p80 is number and p > p80 %}
              brake
            {% elif p is number and p30 is number and p < p30 %}
              cheap
            {% else %}
              neutral
            {% endif %}
          {% endif %}

      #########################################################################
      # Comfort guard active (deadband)
      # - If indoor is meaningfully below target => block price braking
      #########################################################################
      - name: "SVOTC Comfort guard active"
        unique_id: svotc_comfort_guard_active
        state: >
          {% set mode = states('input_select.svotc_mode') %}
          {% set indoor = states('sensor.svotc_src_indoor') | float(none) %}
          {% set target = states('sensor.svotc_dynamic_target_temperature') | float(none) %}
          {% set deadband = 0.2 %}
          {% if mode == 'Off' or indoor is not number or target is not number %}
            false
          {% else %}
            {{ indoor < (target - deadband) }}
          {% endif %}

      #########################################################################
      # Virtual outdoor temperature = outdoor + applied_offset
      #########################################################################
      - name: "SVOTC Virtual outdoor temperature"
        unique_id: svotc_virtual_outdoor_temperature
        unit_of_measurement: "째C"
        device_class: temperature
        state_class: measurement
        state: >
          {% set out = states('sensor.svotc_src_outdoor') | float(none) %}
          {% set off = states('input_number.svotc_applied_offset_c') | float(0) %}
          {% if out is number %}
            {{ (out + off) | round(2) }}
          {% else %}
            {{ states('sensor.svotc_virtual_outdoor_temperature') | float(0) }}
          {% endif %}

  - binary_sensor:
      - name: "SVOTC Price available"
        unique_id: svotc_price_available
        state: >
          {{ states('sensor.svotc_src_current_price') not in ['unknown','unavailable','none',''] }}

###############################################################################
# Dwell / short spike handler (30 minutes)
# - Keeps a stable price state in input_text.svotc_last_price_state
# - Uses input_text.svotc_pending_price_state to avoid resetting dwell timer
###############################################################################
automation:
  - alias: "SVOTC Price dwell (30 min)"
    id: svotc_price_dwell_30min
    mode: single
    trigger:
      - platform: time_pattern
        minutes: "/1"
      - platform: state
        entity_id:
          - sensor.svotc_raw_price_state

    variables:
      dwell_minutes: 30
      raw: "{{ states('sensor.svotc_raw_price_state') }}"
      stable: "{{ states('input_text.svotc_last_price_state') }}"
      pending: "{{ states('input_text.svotc_pending_price_state') }}"

      # Parse the stored datetime safely
      last_changed_dt: >
        {% set s = states('input_datetime.svotc_last_price_state_changed') %}
        {% if s in ['unknown','unavailable','none',''] %}
          {{ none }}
        {% else %}
          {{ as_datetime(s) }}
        {% endif %}

      # Always compute elapsed minutes using timestamps (safe)
      minutes_since_change: >
        {% if last_changed_dt is none %}
          9999
        {% else %}
          {{ ((as_timestamp(now()) - as_timestamp(last_changed_dt)) / 60) | float(0) }}
        {% endif %}

    condition:
      - condition: template
        value_template: "{{ raw not in ['unknown','unavailable','none',''] }}"

    action:
      - choose:
          # If raw equals stable -> align pending to stable
          - conditions:
              - condition: template
                value_template: "{{ raw == stable }}"
            sequence:
              - service: input_text.set_value
                target:
                  entity_id: input_text.svotc_pending_price_state
                data:
                  value: "{{ stable }}"

          # If raw differs from stable and raw is a NEW pending candidate -> start dwell timer
          - conditions:
              - condition: template
                value_template: "{{ raw != stable and raw != pending }}"
            sequence:
              - service: input_text.set_value
                target:
                  entity_id: input_text.svotc_pending_price_state
                data:
                  value: "{{ raw }}"
              - service: input_datetime.set_datetime
                target:
                  entity_id: input_datetime.svotc_last_price_state_changed
                data:
                  datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

          # If raw differs from stable and raw == pending, and dwell passed -> accept stable change
          - conditions:
              - condition: template
                value_template: >
                  {{ raw != stable and raw == pending and minutes_since_change >= dwell_minutes }}
            sequence:
              - service: input_text.set_value
                target:
                  entity_id: input_text.svotc_last_price_state
                data:
                  value: "{{ raw }}"
              - service: input_text.set_value
                target:
                  entity_id: input_text.svotc_pending_price_state
                data:
                  value: "{{ raw }}"
        default: []

  #############################################################################
  # Engine: compute requested_offset + ramp applied_offset
  # - Simplified and stable
  # - Price brake applies positive offset (warmer virtual outdoor => less heat)
  # - Heating applies negative offset (colder virtual outdoor => more heat)
  # - MCP only when requested offset ~ 0 while brake is blocked by comfort guard
  #############################################################################
  - alias: "SVOTC Engine"
    id: svotc_engine
    mode: single
    trigger:
      - platform: time_pattern
        minutes: "/1"
      - platform: state
        entity_id:
          - sensor.svotc_src_indoor
          - sensor.svotc_src_outdoor
          - input_select.svotc_mode
          - input_number.svotc_comfort_temperature
          - input_number.svotc_vacation_temperature
          - input_number.svotc_brake_aggressiveness
          - input_number.svotc_heat_aggressiveness
          - input_text.svotc_last_price_state
          - sensor.svotc_current_price

    variables:
      mode: "{{ states('input_select.svotc_mode') }}"
      indoor: "{{ states('sensor.svotc_src_indoor') | float(none) }}"
      target: "{{ states('sensor.svotc_dynamic_target_temperature') | float(none) }}"

      # Stable price state after dwell
      price_state: "{{ states('input_text.svotc_last_price_state') }}"

      comfort_guard: "{{ is_state('sensor.svotc_comfort_guard_active','true') }}"

      # Aggressiveness mapping (simple)
      brake_aggr: "{{ states('input_number.svotc_brake_aggressiveness') | int(0) }}"
      heat_aggr: "{{ states('input_number.svotc_heat_aggressiveness') | int(0) }}"

      # Max offsets (tune to taste)
      max_brake_offset: "{{ (brake_aggr * 2.0) | float(0) }}"   # 0..10
      max_heat_offset: "{{ (heat_aggr * 2.0) | float(0) }}"     # 0..10 (applied negative)

      deadband: 0.2
      kp: 1.0

      requested: >
        {% if mode == 'Off' %}
          0
        {% elif indoor is not number or target is not number %}
          0
        {% else %}
          {% set err = (target - indoor) %}

          {# Comfort term: heat => negative offset, cool => positive offset #}
          {% set comfort_offset =
              ( (err * -kp)
                if (err | abs) > deadband else 0.0
              )
          %}
          {% if comfort_offset < 0 %}
            {% set comfort_offset = max(comfort_offset, -max_heat_offset) %}
          {% else %}
            {% set comfort_offset = min(comfort_offset, max_brake_offset) %}
          {% endif %}

          {# Price term: brake => positive offset, but blocked if comfort_guard #}
          {% set price_offset = 0.0 %}
          {% if price_state == 'brake' and not comfort_guard %}
            {% set price_offset = max_brake_offset %}
          {% endif %}

          {{ (comfort_offset + price_offset) | round(2) }}
        {% endif %}

      # MCP only when requested offset is ~0 during comfort-blocked braking
      reason: >
        {% set r = requested | float(0) %}
        {% if mode == 'Off' %}
          OFF
        {% elif indoor is not number or target is not number %}
          MISSING_INDOOR
        {% elif price_state == 'brake' and comfort_guard and (r | abs) < 0.05 %}
          MCP
        {% elif price_state == 'brake' and comfort_guard %}
          PRICE_LIMITING_COMFORT
        {% elif price_state == 'brake' %}
          PRICE_BRAKE
        {% else %}
          COMFORT
        {% endif %}

      max_delta: "{{ states('input_number.svotc_max_delta_per_step_c') | float(0.5) }}"
      applied_prev: "{{ states('input_number.svotc_applied_offset_c') | float(0) }}"

      applied_next: >
        {% set r = requested | float(0) %}
        {% set a = applied_prev | float(0) %}
        {% set d = r - a %}
        {% if d > max_delta %}
          {{ (a + max_delta) | round(2) }}
        {% elif d < -max_delta %}
          {{ (a - max_delta) | round(2) }}
        {% else %}
          {{ r | round(2) }}
        {% endif %}

    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.svotc_requested_offset_c
        data:
          value: "{{ requested | float(0) }}"

      - service: input_number.set_value
        target:
          entity_id: input_number.svotc_applied_offset_c
        data:
          value: "{{ applied_next | float(0) }}"

      - service: input_text.set_value
        target:
          entity_id: input_text.svotc_reason_code
        data:
          value: "{{ reason }}"
